// Book Actions 

export const CREATE_BOOK_REQUEST_START = "CREATE_BOOK_REQUEST_START";
export const CREATE_BOOK_REQUEST_SUCCESS = "CREATE_BOOK_REQUEST_SUCCESS";
export const CREATE_BOOK_REQUEST_FAIL = "CREATE_BOOK_REQUEST_FAIL"


// User Actions
